### ISSUE TITLE
Compile errors. 

### ISSUE THREAD

**Issue by SolodovRD** [eyyupT/-Facial-Landmarks---Dlib---OpenCV---CPP---Qt---GUI#1]
So, Thank you for great example. However it is a problem to run this. Qt returns the following errors
:-1: error: gui_main.o: undefined reference to symbol 'cblas_saxpy'
/usr/lib/x86_64-linux-gnu/libcblas.so.3:-1: error: error adding symbols: DSO missing from command line
:-1: error: collect2: error: ld returned 1 exit status

I have blas installed
libatlas-base-dev is already the newest version (3.10.3-5)
I cannot find any solution to resolve this issue. May be you have an Ideas?
Best Regards.

**Comment by eyyupT** [comment]
This issue is not related to my project. It stems from your Dlib Library or OpenCV Library installation.

**Comment by eyyupT** [comment]
You can check following Playlist in my YouTube Channel to find suitable installation with your operating system.

Dlib installations : https://www.youtube.com/playlist?list=PLOl6SW8nLgJxpmjT5jsuDfJAnX-xr7C1U

OpenCV installations : https://www.youtube.com/playlist?list=PLOl6SW8nLgJw-EPXAWP6-zaDXBy1pedDp
